# Build with:
# docker build -t "alex88ridolfi/pulsar-miner-2.0-gpu:lovelace-sm89" -f Dockerfile_pulsar-miner-ubuntu22.04-cuda11.8-lovelace-sm89.txt .

FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

LABEL maintainer="Alessandro Ridolfi <alex88.ridolfi@gmail.com>"

ENV DEBIAN_FRONTEND=noninteractive
ENV PSRHOME=/software

# Consolidated system & dependency installation
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    ca-certificates \
    python3-pip \
    python3-dev \
    nano \
    emacs \
    less \
    latex2html \
    rsync \
    wget \
    # Tempo requirements
    autoconf \
    automake \
    libtool \
    gsl-bin \
    libgsl-dev \
    tcsh \
    gfortran \
    # PRESTO requirements
    libfftw3-bin \
    libfftw3-dev \
    libglib2.0-dev \
    libcfitsio-bin \
    libcfitsio-dev \
    pgplot5 \
    libx11-dev \
    libpng-dev \
    # PrestoZL requirements
    build-essential \
    python-is-python3 \
    && rm -rf /var/lib/apt/lists/*

# Set Python 3.10 as default
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    update-alternatives --install /usr/bin/python  python  /usr/bin/python3.10 1

#######################
# CUDA-SAMPLES
#######################
ARG SAMPLES_SMS=61 89
WORKDIR $PSRHOME
RUN git clone https://github.com/NVIDIA/cuda-samples.git && \
    cd cuda-samples && git checkout 81992093d2b8c33cab22dbf6852c070c330f1715
ENV CUDA_SAMPLES_DIR=${PSRHOME}/cuda-samples
# presto2_on_gpu only consumes headers (helper_cuda.h et al). The full sample
# build is kept for parity with Ridolfi's reference file; if build time hurts,
# this RUN can be dropped and the clone alone is sufficient.
RUN cd $CUDA_SAMPLES_DIR && make -j "$(nproc)" SMS="${SAMPLES_SMS}"

#######################
# TEMPO
#######################
WORKDIR $PSRHOME
RUN git clone https://git.code.sf.net/p/tempo/tempo

ENV TEMPO="${PSRHOME}/tempo"
ENV PATH="${PATH}:${PSRHOME}/tempo/bin"

WORKDIR $PSRHOME/tempo
RUN ./prepare && \
    ./configure --prefix=$PSRHOME/tempo && \
    make -j$(nproc) && \
    make install

RUN python3 -m pip install --no-cache-dir "numpy<2.0.0" 

#######################
# PRESTO2_ON_GPU (Ada Lovelace sm_89)
#######################
WORKDIR $PSRHOME
RUN git clone https://github.com/alex88ridolfi/presto2_on_gpu.git && \
    cd presto2_on_gpu && \
    git checkout tags/cuda-11.6-11.8

ENV PGPLOT_DIR="/usr/lib/pgplot5"
ENV PGPLOT_FONT="/usr/lib/pgplot5/grfont.dat"
ENV PGPLOT_INCLUDES="/usr/include"
ENV PGPLOT_BACKGROUND="white"
ENV PGPLOT_FOREGROUND="black"
ENV PGPLOT_DEV="/xs"

ENV PRESTO="/software/presto2_on_gpu"
ENV PRESTO2_ON_GPU="/software/presto2_on_gpu"
ENV PATH="${PRESTO}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${PRESTO}/lib:${LD_LIBRARY_PATH}"

WORKDIR ${PRESTO}/src

RUN sed -i 's\CUDA_SAMPLES_PATH  ?= \CUDA_SAMPLES_PATH  ?= /software/cuda-samples\g' Makefile
RUN sed -i 's\#       GENCODE_FLAGS    := ${GENCODE_FLAGS} -gencode arch=compute_89\        GENCODE_FLAGS    := ${GENCODE_FLAGS} -gencode arch=compute_89\g' Makefile

RUN make makewisdom
RUN make prep && make


#######################
# PRESTO (Standard / Python modules)
#######################
WORKDIR $PSRHOME
RUN git clone https://github.com/scottransom/presto.git && \
    cd presto && git checkout v4.0

ENV PRESTO="/software/presto"
ENV PATH="${PRESTO}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${PRESTO}/lib:${LD_LIBRARY_PATH}"
ENV LIBRARY_PATH="${PRESTO}/lib:${LIBRARY_PATH}"

WORKDIR ${PRESTO}/src

RUN make makewisdom
RUN make prep && make

WORKDIR ${PRESTO}

RUN python3 -m pip install --no-cache-dir meson-python meson ninja "setuptools<60" wheel matplotlib scipy astropy pkgconfig cython nvidia-ml-py && \
    python3 -m pip install --no-build-isolation .
RUN python3 -c "import presto.presto, presto.sifting; print('presto OK:', presto.__file__)"

#######################
# PrestoZL
#######################
WORKDIR $PSRHOME
RUN git clone https://github.com/haeuslers/PrestoZL.git && \
    cd PrestoZL && git checkout af2e198c3f035171541bc124dc470a37e5747b0f

ENV PRESTOZL=$PSRHOME/PrestoZL

RUN sed -i '/compute_120\|sm_120/d' $PRESTOZL/src/Makefile

RUN cd $PRESTOZL/src && \
    export PRESTO=$PRESTOZL && \
    export PATH=$PRESTOZL/bin:$PATH && \
    export LD_LIBRARY_PATH=$PRESTOZL/lib:$LD_LIBRARY_PATH && \
    make makewisdom && make prep && make

RUN for arch in sm_61 sm_89; do \
      cuobjdump --list-elf $PRESTOZL/lib/libaccelsearch_lib.so | grep -q "$arch" \
        || { echo "FATAL: $arch missing from libaccelsearch_lib.so"; exit 1; }; \
    done && echo "gencode OK: sm_61 sm_89"

#######################
# PULSAR_MINER
#######################
WORKDIR ${PSRHOME}
RUN git clone https://github.com/haeuslers/PULSAR_MINER.git && \
    cd PULSAR_MINER && \
    git checkout PrestoZL2.0
ENV PATH="${PSRHOME}/PULSAR_MINER:${PATH}"





#######################
# SHELL CONFIGURATION & CLEANUP
#######################
RUN echo 'export PS1="\[\e[4;30m\]\u@\h\[\e[0m\]:\[\e[1;10m\]\w\[\e[0m\]\$ (docker)> "' >> ~/.bashrc && \
    touch ~/.bash_aliases && \
    echo 'alias ls="ls --color=auto"' >> ~/.bash_aliases && \
    echo 'alias ll="ls -l"' >> ~/.bash_aliases && \
    echo 'alias LL="ls -lL"' >> ~/.bash_aliases && \
    echo 'alias lt="ls -lrt --color"' >> ~/.bash_aliases && \
    echo 'alias lh="ls -lh --color"' >> ~/.bash_aliases && \
    echo 'alias rm="rm -i"' >> ~/.bash_aliases && \
    echo 'alias cp="cp -i"' >> ~/.bash_aliases && \
    echo 'alias mv="mv -i"' >> ~/.bash_aliases && \
    echo 'alias emacs="emacs -nw"' >> ~/.bash_aliases && \
    echo 'alias presto2_gpu="export PRESTO=/software/presto2_on_gpu && export LD_LIBRARY_PATH=\${PRESTO}/lib:\${LD_LIBRARY_PATH} && export PATH=\${PRESTO}/bin:\${PATH}"' >> ~/.bash_aliases && \
    echo 'alias presto_gpu="export PRESTO=$PRESTOZL; export PATH=$PRESTOZL/bin:\$PATH; export LD_LIBRARY_PATH=$PRESTOZL/lib:\$LD_LIBRARY_PATH; echo PRESTO -> \$PRESTO"' >> ~/.bash_aliases && \
    echo 'alias presto_cpu="export PRESTO=$PSRHOME/presto; export PATH=$PSRHOME/presto/bin:\$PATH; export LD_LIBRARY_PATH=$PSRHOME/presto/lib:\$LD_LIBRARY_PATH; echo PRESTO -> \$PRESTO"' >> ~/.bash_aliases

RUN ldconfig /usr/local/lib

WORKDIR ${PSRHOME}