# Build with:
# docker build -t "alex88ridolfi/pulsar-miner-2.0-gpu:lovelace-sm89" -f Dockerfile_pulsar-miner-ubuntu22.04-cuda11.8-lovelace-sm89.txt .

FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

LABEL maintainer="Alessandro Ridolfi <alex88.ridolfi@gmail.com>"

ENV DEBIAN_FRONTEND=noninteractive
ENV PSRHOME=/software

# Consolidated system & dependency installation
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    ca-certificates \
    python3-pip \
    python3-dev \
    nano \
    emacs \
    less \
    latex2html \
    rsync \
    # Tempo requirements
    autoconf \
    automake \
    libtool \
    gsl-bin \
    libgsl-dev \
    tcsh \
    gfortran \
    # PRESTO requirements
    libfftw3-bin \
    libfftw3-dev \
    libglib2.0-dev \
    libcfitsio-bin \
    libcfitsio-dev \
    pgplot5 \
    libx11-dev \
    libpng-dev \
    && rm -rf /var/lib/apt/lists/*

# Set Python 3.10 as default
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    update-alternatives --install /usr/bin/python  python  /usr/bin/python3.10 1

#######################
# CUDA-SAMPLES
#######################
WORKDIR $PSRHOME
RUN git clone https://github.com/NVIDIA/cuda-samples.git
WORKDIR $PSRHOME/cuda-samples
ENV CUDA=/usr/local/cuda
ENV CUDA_PATH=${CUDA}
ENV LD_LIBRARY_PATH=${CUDA}/lib64:${LD_LIBRARY_PATH}
ENV CUDA_SAMPLES_DIR=${PSRHOME}/cuda-samples
RUN git checkout 81992093d2b8c33cab22dbf6852c070c330f1715
RUN make -j$(nproc) SMS="89"

#######################
# TEMPO
#######################
WORKDIR $PSRHOME
RUN git clone https://git.code.sf.net/p/tempo/tempo

ENV TEMPO="${PSRHOME}/tempo"
ENV PATH="${PATH}:${PSRHOME}/tempo/bin"

WORKDIR $PSRHOME/tempo
RUN ./prepare && \
    ./configure --prefix=$PSRHOME/tempo && \
    make -j$(nproc) && \
    make install

RUN python3 -m pip install --no-cache-dir numpy

#######################
# PRESTO2_ON_GPU (Ada Lovelace sm_89)
#######################
WORKDIR $PSRHOME
RUN git clone https://github.com/alex88ridolfi/presto2_on_gpu.git

ENV PGPLOT_DIR="/usr/lib/pgplot5"
ENV PGPLOT_FONT="/usr/lib/pgplot5/grfont.dat"
ENV PGPLOT_INCLUDES="/usr/include"
ENV PGPLOT_BACKGROUND="white"
ENV PGPLOT_FOREGROUND="black"
ENV PGPLOT_DEV="/xs"

ENV PRESTO="/software/presto2_on_gpu"
ENV PRESTO2_ON_GPU="/software/presto2_on_gpu"
ENV PATH="${PRESTO}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${PRESTO}/lib:${LD_LIBRARY_PATH}"

WORKDIR ${PRESTO}/src

RUN sed -i 's\CUDA_SAMPLES_PATH  ?= \CUDA_SAMPLES_PATH  ?= /software/cuda-samples\g' Makefile
RUN sed -i 's\#       GENCODE_FLAGS    := ${GENCODE_FLAGS} -gencode arch=compute_89\        GENCODE_FLAGS    := ${GENCODE_FLAGS} -gencode arch=compute_89\g' Makefile
RUN make makewisdom && \
    make prep && \
    make

#######################
# PULSAR_MINER
#######################
WORKDIR ${PSRHOME}
RUN git clone https://github.com/alex88ridolfi/PULSAR_MINER.git
ENV PATH="${PSRHOME}/PULSAR_MINER:${PATH}"

#######################
# PRESTO (Standard / Python modules)
#######################
WORKDIR $PSRHOME
RUN git clone https://github.com/alex88ridolfi/presto.git

ENV PRESTO="/software/presto"
ENV PATH="${PRESTO}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${PRESTO}/lib:${LD_LIBRARY_PATH}"
ENV LIBRARY_PATH="${PRESTO}/lib:${LIBRARY_PATH}"

WORKDIR ${PRESTO}/src

RUN make makewisdom && \
    make prep && \
    make

WORKDIR ${PRESTO}

RUN python3 -m pip install --no-cache-dir meson-python meson ninja && \
    python3 -m pip install --no-build-isolation .

#######################
# SHELL CONFIGURATION & CLEANUP
#######################
RUN echo 'export PS1="\[\e[4;30m\]\u@\h\[\e[0m\]:\[\e[1;10m\]\w\[\e[0m\]\$ (docker)> "' >> ~/.bashrc && \
    echo 'alias ls="ls --color=auto"' >> ~/.bashrc && \
    echo 'alias ll="ls -l"' >> ~/.bashrc && \
    echo 'alias LL="ls -lL"' >> ~/.bashrc && \
    echo 'alias lt="ls -lrt --color"' >> ~/.bashrc && \
    echo 'alias lh="ls -lh --color"' >> ~/.bashrc && \
    echo 'alias rm="rm -i"' >> ~/.bashrc && \
    echo 'alias cp="cp -i"' >> ~/.bashrc && \
    echo 'alias mv="mv -i"' >> ~/.bashrc && \
    echo 'alias emacs="emacs -nw"' >> ~/.bashrc && \
    echo 'alias presto_gpu="export PRESTO=/software/presto2_on_gpu && export LD_LIBRARY_PATH=\${PRESTO}/lib:\${LD_LIBRARY_PATH} && export PATH=\${PRESTO}/bin:\${PATH}"' >> ~/.bashrc

RUN ldconfig /usr/local/lib

WORKDIR ${PSRHOME}